### ISSUE TITLE
Specifying K in PML_distribution_approximate(x, K)

### ISSUE THREAD

**Issue by dashar** [dmitrip/PML#2]
If the example of x = [9,3,2,1,1] is used with k>6 (6 is the estimated support size), then the empirical distribution is the pml for k = 5 concatenated with 0's, which seems to be incorrect. The same problem stays in MATLAB.

**Comment by dmitrip** [comment]
This is correct behavior.  As a smaller example, consider x = [2,1,1].  You'll see that the output is uniform on 9 elements for k = 9, but uniform on 3 elements for k = 10 with 7 trailing 0s (and the optimal k is 5, uniform on 5 elements).  To check that this is the correct behavior, you can compare just two cases: uniform on 3 elements with F0 trailing 0s versus uniform on 3+F0 elements, and you'll see that indeed the observed thing happens.

The intuition is that if you're forcing a larger-than-optimal k, you are forcing the nonzero-height bins to mix with a greater number of zero-height bins.  For large enough k, this forced mixing results in low-enough likelihood that it becomes better to keep the zero- and nonzero-height bins in separate clumps, leading to the behavior you observed.  Another way to see it is that the objective function being optimized is -n D(p_empirical || p) + \sum_u log(|X_u|!) - log(F0!), where X_u denotes the subset of the alphabet clumped into a single bin height and F0 is the number of symbols observed 0 times.  Increasing k boosts the second term (since there are more total symbols to clump), but lowers the first term.  Roughly.

Thanks for pointing this out, I hadn't realized this happened.  I can also provide a more detailed computation for the claims in the first paragraph here if it'll help.
