### ISSUE TITLE
Incorrect output?

### ISSUE THREAD

**Issue by logprobability** [dmitrip/PML#4]
Using the python interface,
pml.approximate_PML_from_histogram([100000, 10000, 100, 10, 1, 1]) -> array([9.08166231e-01, 9.08166231e-02, 9.08166231e-04, 9.08166231e-05])

Does that seem correct? I fail to see how a histogram with support size 6 returns a likelihood-maximizing distribution with support size 4...

**Comment by logprobability** [comment]
It may be that this:
"For some inputs, the output p has sum less than 1 (for example, if each symbol occurs once, so empirical_distribution is a vector of ones). The missing probability mass is the "continuous part," distributed over infinitely many unobserved symbols, and the output p is the "discrete part.""

Is what's going on.

**Comment by dmitrip** [comment]
Yes, in this case the approximate PML distribution has a "continuous part."  Another example would be:
pml.approximate_PML_from_histogram([3, 1, 1]) 
which returns array([0.6])

We used the term "continuous part" from this paper by Alon Orlitsky, Narayana Santhanam, Krishnamurthy Viswanathan, Junan Zhang, "On Modeling Profiles instead of Values" from 2012:
https://arxiv.org/abs/1207.4175
and search the paper for "continuous part".

**Comment by dmitrip** [comment]
To add some intuition to this behavior: suppose that your data has histogram [1, 1, 1], that is, 3 different symbols, each observed once.  The probability of 3 different symbols in a sample of size 3 under a uniform distribution on K symbols grows as K increases, since as K gets larger, the probability that at least one symbol repeats gets smaller.  Therefore there is no value of K that maximizes the probability of this event, so we let K -> \infty, and, following the terminology of Orlitsky et al., we say that the PML distribution has "continuous part" (since two draws from a continuous probability distribution repeat with probability 0).

You can see this by trying pml.approximate_PML_from_histogram([1,1,1]), which returns an empty array.  It can also happen that the PML (and approximate PML) distribution can have both a discrete and a continuous part, which is the case in your example, and in an example like [3, 1, 1].

**Comment by logprobability** [comment]
Thank you very much, your explanation and the reference you provided are really helpful!
